apiVersion: v1
kind: Pod
metadata:
  name: testpod
  labels:
    app: javawebapp
spec:
  containers:
  - name: javawebappcon
    image: dockerhandson/java-web-app:1
    ports:
    - containerPort: 8080
  - name: nginxcontainer
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: testsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
  - port: 8080
    targetPort: 8080
    name: tomcat 
  - port: 80
    targetPort: 80
    name: nginx    
