apiVersion: v1
kind: Pod
metadata:
  name: nodejspod
  namespace: test-ns
  labels:
    app: nodeapp
spec:
  containers:
  - name: nodeappcontainer
    image: dockerhandson/node-app-mss:1
    ports:
    - containerPort: 9981  
